### ISSUE TITLE
How to avoid information leakage during homomorphic operations?

### ISSUE THREAD

**Issue by Skyfacon** [zama-ai/fhevm-solidity#345]
Suppose there is such a scenario, A reads the encrypted balance of B in the contract, then through homomorphic operations got another value, finally he views the value and by doing the revert calculation, A can get the balance of B in plain text. I want to know if fhevm has some mechanisms to handle this

**Comment by piu738** [comment]
Broo in this case it's possible that A could get information about the plaintext balance of B. This is known as a "chosen ciphertext attack" . Zama FHEVM does not inherently protect against chosen ciphertext attacks. If u are a developer using Zama FHEVM then design ur protocol and application to ensure that sensitive information is not inadvertently leaked through operations on encrypted data. You can use some techniques such as padding, blinding, or secure multiparty computation to protect against various types of attacks.

**Comment by immortal-tofu** [comment]
> Suppose there is such a scenario, A reads the encrypted balance of B in the contract, then through homomorphic operations got another value, finally he views the value and by doing the revert calculation, A can get the balance of B in plain text. I want to know if fhevm has some mechanisms to handle this

Hello @Skyfacon !
To protect your ciphertext, you need to prevent any contract to access your ciphertext. In an ERC20, it means that all balances are stored with the `private` keyword for example. With this, no other contracts can access balances and compute or decrypt them.
Of course these ciphertexts could be took from the chain directly, you could also add 0 to them offchain, but if you want to decrypt these new ciphertexts, you need to have these onchain and it won't be possible. It won't work because you can't provide a zero-knowledge proof of the ciphertext, proving that you know the content of this ciphertext.

That's why the rule is simple: if your keep your ciphertext (euint8/16/...) as private AND you don't send these values to another contract, your data is safe.
