### ISSUE TITLE
Merge Yuxi's PR

### ISSUE THREAD

**Issue by immortal-tofu** [zama-ai/fhevm-solidity#526]

**Comment by poppyseedDev** [comment]
This issue is related to the following PRs:
https://github.com/zama-ai/fhevm/pull/495
https://github.com/zama-ai/fhevm/pull/496
https://github.com/zama-ai/fhevm/pull/493

The biggest intention of them is apply formatting as specified in [Zama's documentation style guide](https://www.notion.so/zamaai/Zama-Documentation-Style-Guide-05e27bb48432463b990f3946d9d6ecf8). Adding a common style guide across entire Zama's documentation. There was initially some confusion from my side regarding [Page summary](https://www.notion.so/zamaai/Zama-Documentation-Style-Guide-05e27bb48432463b990f3946d9d6ecf8?pvs=4#9e64b60ffeb547e78824f8b53bb17557) since it allowed for repetition, however most of the repetitions have been addressed in the review (see comments).

**Comment by poppyseedDev** [comment]
@immortal-tofu could you quickly check if everything is okay?
